language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: A7VY+0wMlnU62Ney/2w3j7ypXBgGPl8y8keVg/yy5jqQEooevFu8Z5Xbn2gQlKRr9TeoFCPD64HMPA4Eoh+QHCCcZS6/wjkU61J8IYSayOCMm6CBuFvYj3+mPv6Yu1wkm+CEGxCflJhjsiS3Bomv8MeEMdZzsp9ukRRqG09vN26tYSZ+IJ4wDs4XF2GwRoewYWsLpunnNkqxam82/1e0wvITTOyooAsCJf3jjKKNSyGBHgMtrONggiE3iiqIWzmFx8+RG/z0gMRyU4fBn2nGfRGCSEPASvUrCNzlcgfTgrpj4EOYILn2R36MGERqi8oI8AY/KvJgla+SRDSswW+boBqoC3T/GcEmepXWJuxGeZcC6rUsHFYJz3v12mtgLj0SwIAt5AkjR4c8pjKRG4yS9dJTry0ZkrFKxhEG+IVf5hrmWanx4CQYE+reB9ix4bJ/r6Gw/1JsJFmb9vA59W/o1Z42Me9+cO3XEwhyhL5qJXD1VJoCzEodkpS7hiYNx8dZsk6/mLwxXAbQe0ve0D0jyGw/DVB+9UPW5/+AEBWAM91j1uBtirXduiDa6wpVnlKzY7yLKuCBQwbtW0G4Z6YlmpNDhPKPiueYmZW8PCNatXPpFDFZ0CYEokbgyC6XOBxPZA3PGd+qr3/Sz9iyk73pjFbTt5+3B6cHUPhY9d0RfBw=
  app: glacial-beyond-72753
  on:
    repo: dillon-mckee/supTravis
